apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-exporter-config
  namespace: thanos
data:
  blackbox.yml: |-
    modules:
      http_2xx:
        prober: http
        http:
          preferred_ip_protocol: "ip4"
          tls_config:
            insecure_skip_verify: true
      tcp_connect:
        prober: tcp
      icup:
        prober: icup
---
apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter-svc
  namespace: thanos
  labels:
    app: blackbox-exporter
spec:
  type: NodePort
  selector:
    app: blackbox-exporter
  ports:
  - name: http
    protocol: TCP
    port: 9115
    targetPort: 9115
    nodePort: 30012    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter
  namespace: thanos
  labels:
    app: blackbox-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox-exporter
  template:
    metadata:
      labels:
        app: blackbox-exporter
    spec:
      nodeSelector:
        role: removable
      containers:
      - image: harbor.com/prometheus/blackbox-exporter:v0.21.0
        name: blackbox-exporter
        args:
          - --config.file=/config/blackbox.yml
        ports:
        - containerPort: 9115
          name: http
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 60
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 60
        resources:
          limits:
            cpu: 1000m
            memory: 1280Mi
          requests:
            cpu: 250m
            memory: 640Mi
        volumeMounts:
        - name: blackbox-config
          mountPath: /config/blackbox.yml
          subPath: blackbox.yml
      restartPolicy: Always
      volumes:
      - name: blackbox-config
        configMap:
          name: blackbox-exporter-config
          items:
          - key: blackbox.yml
            path: blackbox.yml
      hostAliases:
      - ip: "192.168.10.22"
        hostnames:
          - "kibana.com"
          - "grafana.com"
          - "gitlab.com"
          - "jenkins.com"