apiVersion: v1
kind: Service
metadata:
  name: es-exporter-svc
  namespace: thanos
  labels:
    app: es-exporter
spec:
  selector:
    app: es-exporter
  type: ClusterIP
  ports:
  - name: http
    port: 9114
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-exporter
  namespace: thanos
  labels:
    app: es-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: es-exporter
  template:
    metadata:
      labels:
        app: es-exporter
    spec:
      containers:
      - command:
        - /bin/elasticsearch_exporter
        - --es.uri=https://elastic:password@192.168.10.22:31715
        - --es.timeout=60s
        - --es.indices
        - --es.all
        - --es.ssl-skip-verify
        image: harbor.com/prometheus/elasticsearch-exporter:v1.3.0
        securityContext:
          capabilities:
            drop:
            - SETPCAP
            - MKNOD
            - AUDIT_WRITE
            - CHOWN
            - NET_RAW
            - DAC_OVERRIDE
            - FOWNER
            - FSETID
            - KILL
            - SETGID
            - SETUID
            - NET_BIND_SERVICE
            - SYS_CHROOT
            - SETFCAP
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 60
        name: es-exporter
        ports:
        - containerPort: 9114
          name: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 60
        resources:
          limits:
            cpu: 1000m
            memory: 1280Mi
          requests:
            cpu: 250m
            memory: 640Mi
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsGroup: 10000
        runAsUser: 10000
        fsGroup: 10000