apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter-svc
  namespace: thanos
  labels:
    app: kafka-exporter
spec:
  selector:
    app: kafka-exporter
  type: ClusterIP
  ports:
  - name: http
    port: 9308
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  namespace: thanos
  labels:
    app: kafka-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-exporter
  template:
    metadata:
      labels:
        app: kafka-exporter
    spec:
      containers:
      - args:
        - --kafka.server=192.168.10.3:9092
        - --kafka.server=192.168.10.4:9092
        - --kafka.server=192.168.10.5:9092
        - --kafka.server=192.168.10.12:9092
        - --kafka.server=192.168.10.13:9092
        - --kafka.server=192.168.10.54:9092
        - --kafka.server=192.168.10.62:9092
        - --kafka.server=192.168.10.63:9092
        - --kafka.server=192.168.10.72:9092
        image: harbor.com/prometheus/kafka-exporter:1.4.2
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 60
        name: kafka-exporter
        ports:
        - containerPort: 9308
          name: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 60
        resources:
          limits:
            cpu: 1000m
            memory: 1280Mi
          requests:
            cpu: 250m
            memory: 640Mi
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsGroup: 10000
        runAsUser: 10000
        fsGroup: 10000