apiVersion: v1
kind: Secret
metadata:
  name: thanos-objectstorage
  namespace: thanos
type: Opaque
stringData:
  storage.yaml: |
    type: s3
    config:
      bucket: thanos-nj-test
      endpoint: 192.168.10.200:40000
      access_key: access_key
      secret_key: secret_key
      insecure: true
      signature_version2: false